version: '3'

services:
  app:
    build: ../
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - ./instance:/app/instance
