- name: THIS IS NAME
  hosts: "{{ target }}"
  remote_user: xpmans
  become: yes
  vars:
    state_action: "{{ state_action | default('___NOT_SET___') }}"
  roles:
    - {'role': 'create_linux_user', 'vars': {'foo_action': 'present'}}
    - {'role': 'create_user_directory', 'vars': {'state_action': 'directory'}}
    - {'role': 'install_mysql_module', 'vars': {}}
    - {'role': 'create_db', 'vars': {'state_action': 'present'}}
    - {'role': 'create_db_user', 'vars': {'state_action': 'present'}}
    - {'role': 'create_php_fpm_sock'}
    - {'role': 'create_self-signed_certificate', 'vars': {}}
    - {'role': 'create_apache_virtualhost', 'vars': {}}
    - {'role': 'create_ftp_user', 'vars': {}}
    - {'role': 'restart_apache', 'vars': {}}
